teleop:
  move:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: cmd_vel
    deadman_buttons: [7]
    axis_mappings:
      -
        axis: 3
        target: linear.x
        scale: 0.7
      -
        axis: 2
        target: angular.z
        scale: 0.7

  nerf:
    type: topic
    message_type: std_msgs/Int16
    topic_name: nerf_trigger
    message_value:
      target: data
      value: 1
